service: dynamo-eventos-pizzaria

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: 'us-east-1'
  memorySize: 128
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
            

functions:
  readStream:
    handler: handler.handler
    events:
      - stream:
          type: dynamodb
          arn: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/eventos-pizzaria/stream/2023-10-07T22:25:12.785
          batchSize: 1
          maximumRetryAttempts: 10
          enabled: true