service: sqs-status-done

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: 'us-east-1'
  memorySize: 128
  lambdaHashingVersion: "20201221"
  iam:
    role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
            

functions:
          
  detail:
    handler: handler.handler
    events:
      - eventBridge:
          eventBus:
            - arn:aws:events:${aws:region}:${aws:accountId}:event-bus/pizzaria
          pattern:
            source:
              - com.pizza.status
            detail-type:
              - Alteracao Pizza
            detail:
              status:
                - pronto